// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: clicks.sql

package dbgen

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const countAllClicks = `-- name: CountAllClicks :one
SELECT COUNT(*) FROM clicks
`

func (q *Queries) CountAllClicks(ctx context.Context) (int64, error) {
	row := q.db.QueryRow(ctx, countAllClicks)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createClick = `-- name: CreateClick :one
INSERT INTO clicks (user_id, url_id, device, browser, latitude, longitude)
VALUES ($1, $2, $3, $4, $5, $6)
RETURNING id, user_id, url_id, device, browser, latitude, longitude, created_at, updated_at
`

type CreateClickParams struct {
	UserID    pgtype.UUID
	UrlID     pgtype.UUID
	Device    pgtype.Text
	Browser   pgtype.Text
	Latitude  pgtype.Numeric
	Longitude pgtype.Numeric
}

func (q *Queries) CreateClick(ctx context.Context, arg CreateClickParams) (Click, error) {
	row := q.db.QueryRow(ctx, createClick,
		arg.UserID,
		arg.UrlID,
		arg.Device,
		arg.Browser,
		arg.Latitude,
		arg.Longitude,
	)
	var i Click
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.UrlID,
		&i.Device,
		&i.Browser,
		&i.Latitude,
		&i.Longitude,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getBrowserStatsByURLID = `-- name: GetBrowserStatsByURLID :many
SELECT 
    COALESCE(browser, 'Unknown') AS browser,
    COUNT(*) AS count
FROM clicks
WHERE url_id = $1
GROUP BY browser
ORDER BY count DESC
`

type GetBrowserStatsByURLIDRow struct {
	Browser string
	Count   int64
}

func (q *Queries) GetBrowserStatsByURLID(ctx context.Context, urlID pgtype.UUID) ([]GetBrowserStatsByURLIDRow, error) {
	rows, err := q.db.Query(ctx, getBrowserStatsByURLID, urlID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetBrowserStatsByURLIDRow
	for rows.Next() {
		var i GetBrowserStatsByURLIDRow
		if err := rows.Scan(&i.Browser, &i.Count); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getClickByID = `-- name: GetClickByID :one
SELECT id, user_id, url_id, device, browser, latitude, longitude, created_at, updated_at FROM clicks WHERE id = $1
`

func (q *Queries) GetClickByID(ctx context.Context, id uuid.UUID) (Click, error) {
	row := q.db.QueryRow(ctx, getClickByID, id)
	var i Click
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.UrlID,
		&i.Device,
		&i.Browser,
		&i.Latitude,
		&i.Longitude,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getClickCountByURLID = `-- name: GetClickCountByURLID :one
SELECT COUNT(*) FROM clicks WHERE url_id = $1
`

func (q *Queries) GetClickCountByURLID(ctx context.Context, urlID pgtype.UUID) (int64, error) {
	row := q.db.QueryRow(ctx, getClickCountByURLID, urlID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const getClickCountByUserID = `-- name: GetClickCountByUserID :one
SELECT COUNT(*) FROM clicks WHERE user_id = $1
`

func (q *Queries) GetClickCountByUserID(ctx context.Context, userID pgtype.UUID) (int64, error) {
	row := q.db.QueryRow(ctx, getClickCountByUserID, userID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const getClickCountsByURLIDs = `-- name: GetClickCountsByURLIDs :many
SELECT url_id, COUNT(*)::bigint AS click_count
FROM clicks
WHERE url_id = ANY($1::uuid[])
GROUP BY url_id
`

type GetClickCountsByURLIDsRow struct {
	UrlID      pgtype.UUID
	ClickCount int64
}

func (q *Queries) GetClickCountsByURLIDs(ctx context.Context, dollar_1 []uuid.UUID) ([]GetClickCountsByURLIDsRow, error) {
	rows, err := q.db.Query(ctx, getClickCountsByURLIDs, dollar_1)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetClickCountsByURLIDsRow
	for rows.Next() {
		var i GetClickCountsByURLIDsRow
		if err := rows.Scan(&i.UrlID, &i.ClickCount); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getClickStatsByDateRange = `-- name: GetClickStatsByDateRange :many
SELECT 
    DATE(created_at) as date,
    COUNT(*) as click_count
FROM clicks 
WHERE url_id = $1 AND created_at BETWEEN $2 AND $3
GROUP BY DATE(created_at)
ORDER BY date DESC
`

type GetClickStatsByDateRangeParams struct {
	UrlID       pgtype.UUID
	CreatedAt   pgtype.Timestamptz
	CreatedAt_2 pgtype.Timestamptz
}

type GetClickStatsByDateRangeRow struct {
	Date       pgtype.Date
	ClickCount int64
}

func (q *Queries) GetClickStatsByDateRange(ctx context.Context, arg GetClickStatsByDateRangeParams) ([]GetClickStatsByDateRangeRow, error) {
	rows, err := q.db.Query(ctx, getClickStatsByDateRange, arg.UrlID, arg.CreatedAt, arg.CreatedAt_2)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetClickStatsByDateRangeRow
	for rows.Next() {
		var i GetClickStatsByDateRangeRow
		if err := rows.Scan(&i.Date, &i.ClickCount); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getClickStatsByURLID = `-- name: GetClickStatsByURLID :one
SELECT 
    COUNT(*) as total_clicks,
    COUNT(DISTINCT device) as unique_devices,
    COUNT(DISTINCT browser) as unique_browsers
FROM clicks WHERE url_id = $1
`

type GetClickStatsByURLIDRow struct {
	TotalClicks    int64
	UniqueDevices  int64
	UniqueBrowsers int64
}

func (q *Queries) GetClickStatsByURLID(ctx context.Context, urlID pgtype.UUID) (GetClickStatsByURLIDRow, error) {
	row := q.db.QueryRow(ctx, getClickStatsByURLID, urlID)
	var i GetClickStatsByURLIDRow
	err := row.Scan(&i.TotalClicks, &i.UniqueDevices, &i.UniqueBrowsers)
	return i, err
}

const getClicksByURLID = `-- name: GetClicksByURLID :many
SELECT id, user_id, url_id, device, browser, latitude, longitude, created_at, updated_at FROM clicks WHERE url_id = $1 ORDER BY created_at DESC LIMIT $2 OFFSET $3
`

type GetClicksByURLIDParams struct {
	UrlID  pgtype.UUID
	Limit  int32
	Offset int32
}

func (q *Queries) GetClicksByURLID(ctx context.Context, arg GetClicksByURLIDParams) ([]Click, error) {
	rows, err := q.db.Query(ctx, getClicksByURLID, arg.UrlID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Click
	for rows.Next() {
		var i Click
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.UrlID,
			&i.Device,
			&i.Browser,
			&i.Latitude,
			&i.Longitude,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getClicksByUserID = `-- name: GetClicksByUserID :many
SELECT id, user_id, url_id, device, browser, latitude, longitude, created_at, updated_at FROM clicks WHERE user_id = $1 ORDER BY created_at DESC LIMIT $2 OFFSET $3
`

type GetClicksByUserIDParams struct {
	UserID pgtype.UUID
	Limit  int32
	Offset int32
}

func (q *Queries) GetClicksByUserID(ctx context.Context, arg GetClicksByUserIDParams) ([]Click, error) {
	rows, err := q.db.Query(ctx, getClicksByUserID, arg.UserID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Click
	for rows.Next() {
		var i Click
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.UrlID,
			&i.Device,
			&i.Browser,
			&i.Latitude,
			&i.Longitude,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getDeviceStatsByURLID = `-- name: GetDeviceStatsByURLID :many
SELECT 
    COALESCE(device, 'Unknown') AS device,
    COUNT(*) AS count
FROM clicks
WHERE url_id = $1
GROUP BY device
ORDER BY count DESC
`

type GetDeviceStatsByURLIDRow struct {
	Device string
	Count  int64
}

func (q *Queries) GetDeviceStatsByURLID(ctx context.Context, urlID pgtype.UUID) ([]GetDeviceStatsByURLIDRow, error) {
	rows, err := q.db.Query(ctx, getDeviceStatsByURLID, urlID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetDeviceStatsByURLIDRow
	for rows.Next() {
		var i GetDeviceStatsByURLIDRow
		if err := rows.Scan(&i.Device, &i.Count); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getRecentClicks = `-- name: GetRecentClicks :many
SELECT id, user_id, url_id, device, browser, latitude, longitude, created_at, updated_at FROM clicks ORDER BY created_at DESC LIMIT $1 OFFSET $2
`

type GetRecentClicksParams struct {
	Limit  int32
	Offset int32
}

func (q *Queries) GetRecentClicks(ctx context.Context, arg GetRecentClicksParams) ([]Click, error) {
	rows, err := q.db.Query(ctx, getRecentClicks, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Click
	for rows.Next() {
		var i Click
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.UrlID,
			&i.Device,
			&i.Browser,
			&i.Latitude,
			&i.Longitude,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
