// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package dbgen

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Click struct {
	ID        pgtype.UUID
	UserID    pgtype.UUID
	UrlID     pgtype.UUID
	Device    pgtype.Text
	Browser   pgtype.Text
	Latitude  pgtype.Numeric
	Longitude pgtype.Numeric
	CreatedAt pgtype.Timestamptz
	UpdatedAt pgtype.Timestamptz
}

type Role struct {
	ID          pgtype.UUID
	Name        string
	Description pgtype.Text
	CreatedAt   pgtype.Timestamptz
	UpdatedAt   pgtype.Timestamptz
}

type Url struct {
	ID          pgtype.UUID
	ShortUrl    string
	OriginalUrl string
	UserID      pgtype.UUID
	IsActive    pgtype.Bool
	CreatedAt   pgtype.Timestamptz
	UpdatedAt   pgtype.Timestamptz
}

type User struct {
	ID           pgtype.UUID
	Email        string
	PasswordHash string
	FirstName    string
	LastName     string
	RoleID       pgtype.UUID
	IsActive     pgtype.Bool
	CreatedAt    pgtype.Timestamptz
	UpdatedAt    pgtype.Timestamptz
}
