// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: urls.sql

package dbgen

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const countActiveURLs = `-- name: CountActiveURLs :one
SELECT COUNT(*) FROM urls WHERE is_active = true
`

func (q *Queries) CountActiveURLs(ctx context.Context) (int64, error) {
	row := q.db.QueryRow(ctx, countActiveURLs)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countAllURLs = `-- name: CountAllURLs :one
SELECT COUNT(*) FROM urls WHERE is_active = true
`

func (q *Queries) CountAllURLs(ctx context.Context) (int64, error) {
	row := q.db.QueryRow(ctx, countAllURLs)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countAllURLsAdmin = `-- name: CountAllURLsAdmin :one
SELECT COUNT(*) FROM urls
`

func (q *Queries) CountAllURLsAdmin(ctx context.Context) (int64, error) {
	row := q.db.QueryRow(ctx, countAllURLsAdmin)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countAllURLsByDate = `-- name: CountAllURLsByDate :one
SELECT COUNT(*) FROM urls WHERE is_active = true AND created_at BETWEEN $1 AND $2
`

type CountAllURLsByDateParams struct {
	CreatedAt   pgtype.Timestamptz
	CreatedAt_2 pgtype.Timestamptz
}

func (q *Queries) CountAllURLsByDate(ctx context.Context, arg CountAllURLsByDateParams) (int64, error) {
	row := q.db.QueryRow(ctx, countAllURLsByDate, arg.CreatedAt, arg.CreatedAt_2)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countInactiveURLs = `-- name: CountInactiveURLs :one
SELECT COUNT(*) FROM urls WHERE is_active = false
`

func (q *Queries) CountInactiveURLs(ctx context.Context) (int64, error) {
	row := q.db.QueryRow(ctx, countInactiveURLs)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countSearchURLs = `-- name: CountSearchURLs :one
SELECT COUNT(*) FROM urls 
WHERE (short_url ILIKE $1 OR original_url ILIKE $1)
`

func (q *Queries) CountSearchURLs(ctx context.Context, shortUrl string) (int64, error) {
	row := q.db.QueryRow(ctx, countSearchURLs, shortUrl)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createURL = `-- name: CreateURL :one
INSERT INTO urls (original_url, short_url, user_id)
VALUES ($1, $2, $3)
RETURNING id, short_url, original_url, user_id, is_active, created_at, updated_at
`

type CreateURLParams struct {
	OriginalUrl string
	ShortUrl    string
	UserID      pgtype.UUID
}

func (q *Queries) CreateURL(ctx context.Context, arg CreateURLParams) (Url, error) {
	row := q.db.QueryRow(ctx, createURL, arg.OriginalUrl, arg.ShortUrl, arg.UserID)
	var i Url
	err := row.Scan(
		&i.ID,
		&i.ShortUrl,
		&i.OriginalUrl,
		&i.UserID,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteURL = `-- name: DeleteURL :exec
UPDATE urls SET is_active = false, updated_at = NOW() WHERE id = $1
`

func (q *Queries) DeleteURL(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, deleteURL, id)
	return err
}

const getTopURLsByClicks = `-- name: GetTopURLsByClicks :many
SELECT u.id, u.short_url, u.original_url, u.user_id, u.is_active, u.created_at, u.updated_at,
    COUNT(c.id) AS click_count
FROM urls u
LEFT JOIN clicks c ON c.url_id = u.id
WHERE u.is_active = true
GROUP BY u.id
ORDER BY click_count DESC
LIMIT $1
`

type GetTopURLsByClicksRow struct {
	ID          uuid.UUID
	ShortUrl    string
	OriginalUrl string
	UserID      pgtype.UUID
	IsActive    pgtype.Bool
	CreatedAt   pgtype.Timestamptz
	UpdatedAt   pgtype.Timestamptz
	ClickCount  int64
}

func (q *Queries) GetTopURLsByClicks(ctx context.Context, limit int32) ([]GetTopURLsByClicksRow, error) {
	rows, err := q.db.Query(ctx, getTopURLsByClicks, limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetTopURLsByClicksRow
	for rows.Next() {
		var i GetTopURLsByClicksRow
		if err := rows.Scan(
			&i.ID,
			&i.ShortUrl,
			&i.OriginalUrl,
			&i.UserID,
			&i.IsActive,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.ClickCount,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getURLByID = `-- name: GetURLByID :one
SELECT id, short_url, original_url, user_id, is_active, created_at, updated_at FROM urls WHERE id = $1
`

func (q *Queries) GetURLByID(ctx context.Context, id uuid.UUID) (Url, error) {
	row := q.db.QueryRow(ctx, getURLByID, id)
	var i Url
	err := row.Scan(
		&i.ID,
		&i.ShortUrl,
		&i.OriginalUrl,
		&i.UserID,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getURLByShortURL = `-- name: GetURLByShortURL :one
SELECT id, short_url, original_url, user_id, is_active, created_at, updated_at FROM urls WHERE short_url = $1 AND is_active = true
`

func (q *Queries) GetURLByShortURL(ctx context.Context, shortUrl string) (Url, error) {
	row := q.db.QueryRow(ctx, getURLByShortURL, shortUrl)
	var i Url
	err := row.Scan(
		&i.ID,
		&i.ShortUrl,
		&i.OriginalUrl,
		&i.UserID,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getURLCount = `-- name: GetURLCount :one
SELECT COUNT(*) FROM urls WHERE user_id = $1
`

func (q *Queries) GetURLCount(ctx context.Context, userID pgtype.UUID) (int64, error) {
	row := q.db.QueryRow(ctx, getURLCount, userID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const listAllURLs = `-- name: ListAllURLs :many
SELECT id, short_url, original_url, user_id, is_active, created_at, updated_at FROM urls WHERE is_active = true LIMIT $1 OFFSET $2
`

type ListAllURLsParams struct {
	Limit  int32
	Offset int32
}

func (q *Queries) ListAllURLs(ctx context.Context, arg ListAllURLsParams) ([]Url, error) {
	rows, err := q.db.Query(ctx, listAllURLs, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Url
	for rows.Next() {
		var i Url
		if err := rows.Scan(
			&i.ID,
			&i.ShortUrl,
			&i.OriginalUrl,
			&i.UserID,
			&i.IsActive,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listAllURLsAdmin = `-- name: ListAllURLsAdmin :many
SELECT id, short_url, original_url, user_id, is_active, created_at, updated_at FROM urls 
ORDER BY is_active DESC, created_at DESC 
LIMIT $1 OFFSET $2
`

type ListAllURLsAdminParams struct {
	Limit  int32
	Offset int32
}

func (q *Queries) ListAllURLsAdmin(ctx context.Context, arg ListAllURLsAdminParams) ([]Url, error) {
	rows, err := q.db.Query(ctx, listAllURLsAdmin, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Url
	for rows.Next() {
		var i Url
		if err := rows.Scan(
			&i.ID,
			&i.ShortUrl,
			&i.OriginalUrl,
			&i.UserID,
			&i.IsActive,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listAllURLsAdminByName = `-- name: ListAllURLsAdminByName :many
SELECT id, short_url, original_url, user_id, is_active, created_at, updated_at FROM urls 
ORDER BY is_active DESC, short_url ASC 
LIMIT $1 OFFSET $2
`

type ListAllURLsAdminByNameParams struct {
	Limit  int32
	Offset int32
}

func (q *Queries) ListAllURLsAdminByName(ctx context.Context, arg ListAllURLsAdminByNameParams) ([]Url, error) {
	rows, err := q.db.Query(ctx, listAllURLsAdminByName, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Url
	for rows.Next() {
		var i Url
		if err := rows.Scan(
			&i.ID,
			&i.ShortUrl,
			&i.OriginalUrl,
			&i.UserID,
			&i.IsActive,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listAllURLsByDate = `-- name: ListAllURLsByDate :many
SELECT id, short_url, original_url, user_id, is_active, created_at, updated_at FROM urls WHERE is_active = true ORDER BY created_at DESC LIMIT $1 OFFSET $2
`

type ListAllURLsByDateParams struct {
	Limit  int32
	Offset int32
}

func (q *Queries) ListAllURLsByDate(ctx context.Context, arg ListAllURLsByDateParams) ([]Url, error) {
	rows, err := q.db.Query(ctx, listAllURLsByDate, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Url
	for rows.Next() {
		var i Url
		if err := rows.Scan(
			&i.ID,
			&i.ShortUrl,
			&i.OriginalUrl,
			&i.UserID,
			&i.IsActive,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listURLs = `-- name: ListURLs :many
SELECT id, short_url, original_url, user_id, is_active, created_at, updated_at FROM urls WHERE user_id = $1 ORDER BY is_active DESC, created_at DESC LIMIT $2 OFFSET $3
`

type ListURLsParams struct {
	UserID pgtype.UUID
	Limit  int32
	Offset int32
}

func (q *Queries) ListURLs(ctx context.Context, arg ListURLsParams) ([]Url, error) {
	rows, err := q.db.Query(ctx, listURLs, arg.UserID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Url
	for rows.Next() {
		var i Url
		if err := rows.Scan(
			&i.ID,
			&i.ShortUrl,
			&i.OriginalUrl,
			&i.UserID,
			&i.IsActive,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listURLsByClicks = `-- name: ListURLsByClicks :many
SELECT u.id, u.short_url, u.original_url, u.user_id, u.is_active, u.created_at, u.updated_at,
    COUNT(c.id) AS click_count
FROM urls u
LEFT JOIN clicks c ON c.url_id = u.id
GROUP BY u.id
ORDER BY click_count DESC
LIMIT $1 OFFSET $2
`

type ListURLsByClicksParams struct {
	Limit  int32
	Offset int32
}

type ListURLsByClicksRow struct {
	ID          uuid.UUID
	ShortUrl    string
	OriginalUrl string
	UserID      pgtype.UUID
	IsActive    pgtype.Bool
	CreatedAt   pgtype.Timestamptz
	UpdatedAt   pgtype.Timestamptz
	ClickCount  int64
}

func (q *Queries) ListURLsByClicks(ctx context.Context, arg ListURLsByClicksParams) ([]ListURLsByClicksRow, error) {
	rows, err := q.db.Query(ctx, listURLsByClicks, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListURLsByClicksRow
	for rows.Next() {
		var i ListURLsByClicksRow
		if err := rows.Scan(
			&i.ID,
			&i.ShortUrl,
			&i.OriginalUrl,
			&i.UserID,
			&i.IsActive,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.ClickCount,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const searchURLs = `-- name: SearchURLs :many
SELECT id, short_url, original_url, user_id, is_active, created_at, updated_at FROM urls 
WHERE (short_url ILIKE $1 OR original_url ILIKE $1)
ORDER BY is_active DESC, created_at DESC 
LIMIT $2 OFFSET $3
`

type SearchURLsParams struct {
	ShortUrl string
	Limit    int32
	Offset   int32
}

func (q *Queries) SearchURLs(ctx context.Context, arg SearchURLsParams) ([]Url, error) {
	rows, err := q.db.Query(ctx, searchURLs, arg.ShortUrl, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Url
	for rows.Next() {
		var i Url
		if err := rows.Scan(
			&i.ID,
			&i.ShortUrl,
			&i.OriginalUrl,
			&i.UserID,
			&i.IsActive,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateURL = `-- name: UpdateURL :one
UPDATE urls SET original_url = $2, short_url = $3, updated_at = NOW() WHERE id = $1 AND is_active = true RETURNING id, short_url, original_url, user_id, is_active, created_at, updated_at
`

type UpdateURLParams struct {
	ID          uuid.UUID
	OriginalUrl string
	ShortUrl    string
}

func (q *Queries) UpdateURL(ctx context.Context, arg UpdateURLParams) (Url, error) {
	row := q.db.QueryRow(ctx, updateURL, arg.ID, arg.OriginalUrl, arg.ShortUrl)
	var i Url
	err := row.Scan(
		&i.ID,
		&i.ShortUrl,
		&i.OriginalUrl,
		&i.UserID,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateURLStatus = `-- name: UpdateURLStatus :one
UPDATE urls SET is_active = $2, updated_at = NOW() WHERE id = $1 RETURNING id, short_url, original_url, user_id, is_active, created_at, updated_at
`

type UpdateURLStatusParams struct {
	ID       uuid.UUID
	IsActive pgtype.Bool
}

func (q *Queries) UpdateURLStatus(ctx context.Context, arg UpdateURLStatusParams) (Url, error) {
	row := q.db.QueryRow(ctx, updateURLStatus, arg.ID, arg.IsActive)
	var i Url
	err := row.Scan(
		&i.ID,
		&i.ShortUrl,
		&i.OriginalUrl,
		&i.UserID,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
