package middleware

import (
	"context"
	"crypto/rand"
	"encoding/hex"
	"fmt"
	"sync"
	"time"

	"github.com/gin-gonic/gin"
	"github.com/redis/go-redis/v9"
)

// DemoQuotaCookie names the cookie that ties anonymous demo links to a visitor.
const DemoQuotaCookie = "su_demo_id"

type demoQuotaEntry struct {
	count       int
	windowStart time.Time
}

// DemoQuota limits anonymous URL creation (the "free demo") per visitor.
// Identity is the demo cookie when present, always backed by the client IP so
// cookie-less or cookie-clearing clients stay limited too.
type DemoQuota struct {
	redis  *redis.Client
	limit  int
	window time.Duration

	mu  sync.RWMutex
	mem map[string]*demoQuotaEntry
}

func NewDemoQuota(redis *redis.Client, limit int, windowHours int) *DemoQuota {
	if limit <= 0 {
		limit = 3
	}
	if windowHours <= 0 {
		windowHours = 24
	}
	return &DemoQuota{
		redis:  redis,
		limit:  limit,
		window: time.Duration(windowHours) * time.Hour,
		mem:    make(map[string]*demoQuotaEntry),
	}
}

func randomID() string {
	b := make([]byte, 16)
	if _, err := rand.Read(b); err != nil {
		return fmt.Sprintf("%d", time.Now().UnixNano())
	}
	return hex.EncodeToString(b)
}

// visitorIDs returns the identities to count against: the demo cookie (created
// lazily if absent) and the client IP.
func (q *DemoQuota) visitorIDs(c *gin.Context) (string, string) {
	cookieID, err := c.Cookie(DemoQuotaCookie)
	if err != nil || cookieID == "" {
		cookieID = randomID()
		c.Set("demo_cookie", cookieID)
	}
	return cookieID, c.ClientIP()
}

func (q *DemoQuota) redisKey(id string, windowNum int64) string {
	return fmt.Sprintf("demo:quota:%s:%d", id, windowNum)
}

// inc increments one identity and reports whether it is within the limit.
func (q *DemoQuota) inc(ctx context.Context, id string) (bool, int) {
	if q.redis != nil {
		windowNum := time.Now().Unix() / int64(q.window.Seconds())
		key := q.redisKey(id, windowNum)

		count, err := q.redis.Incr(ctx, key).Result()
		if err != nil {
			return q.memInc(id)
		}
		if count == 1 {
			q.redis.Expire(ctx, key, q.window)
		}
		if count > int64(q.limit) {
			q.redis.Decr(ctx, key)
			return false, 0
		}
		return true, q.limit - int(count)
	}
	return q.memInc(id)
}

func (q *DemoQuota) memInc(id string) (bool, int) {
	q.mu.Lock()
	defer q.mu.Unlock()

	now := time.Now()
	entry, ok := q.mem[id]
	if !ok || now.Sub(entry.windowStart) > q.window {
		entry = &demoQuotaEntry{count: 0, windowStart: now}
		q.mem[id] = entry
	}
	entry.count++
	if entry.count > q.limit {
		entry.count--
		return false, 0
	}
	return true, q.limit - entry.count
}

func (q *DemoQuota) dec(ctx context.Context, id string) {
	if q.redis != nil {
		windowNum := time.Now().Unix() / int64(q.window.Seconds())
		q.redis.Decr(ctx, q.redisKey(id, windowNum))
		return
	}
	q.mu.Lock()
	defer q.mu.Unlock()
	if entry, ok := q.mem[id]; ok && entry.count > 0 {
		entry.count--
	}
}

// Take atomically increments the visitor's counters and reports whether the
// request is within the anonymous limit. On failure nothing is consumed.
func (q *DemoQuota) Take(c *gin.Context) (bool, int) {
	cookieID, ip := q.visitorIDs(c)
	okC, remC := q.inc(c.Request.Context(), cookieID)
	okI, remI := q.inc(c.Request.Context(), ip)

	if !okC || !okI {
		if okC {
			q.dec(c.Request.Context(), cookieID)
		}
		if okI {
			q.dec(c.Request.Context(), ip)
		}
		return false, 0
	}

	remaining := remC
	if remI < remaining {
		remaining = remI
	}
	return true, remaining
}

// Release decrements the visitor's counters (used when URL creation fails).
func (q *DemoQuota) Release(c *gin.Context) {
	cookieID, ip := q.visitorIDs(c)
	q.dec(c.Request.Context(), cookieID)
	q.dec(c.Request.Context(), ip)
}

// EnsureCookie persists the demo cookie generated by Take on the response.
func (q *DemoQuota) EnsureCookie(c *gin.Context) {
	if raw, ok := c.Get("demo_cookie"); ok {
		if id, ok := raw.(string); ok && id != "" {
			c.SetCookie(DemoQuotaCookie, id, int(q.window.Seconds()), "/", "", false, true)
		}
	}
}
